<h1>Traditional Models</h1>

<p>This notebook is used to train and explore a series of machine learning models including logistic regression, linear support vector classification (SVC), and an ensemble of binary random forest classifiers</p>

In [1]:
import tradmodels as tmodel

<h1>Training the Binary Classifier Ensemble</h1>

<p>If you need to retrain the models, be sure to restart the runtime</p>

<h3>Train below</h3>

In [2]:
'''define the filepaths for your data here!'''

output_label='testing_1_12-30'
training_set_path='Data/CWT Data/Single/'
test_set_path='Data/CWT Data/Mixed/'

In [4]:
'''train the model'''
test_outputs_df,model_ls,pca_ls=tmodel.model_set(training_set_path,test_set_path,output_label,False)

Master data set shape is (71674, 951) 

 Master data set is
                                150       151       152       153       154  \
albite_train_015s_5250-0 -0.060426  0.364363  0.655384  0.748199  0.667854   
albite_train_015s_5250-1 -0.050979  0.370427  0.661060  0.755651  0.676321   
albite_train_015s_5250-2 -0.065293  0.378984  0.688549  0.793750  0.715698   
albite_train_015s_5250-3 -0.054342  0.375322  0.671679  0.768352  0.688044   
albite_train_015s_5250-4 -0.054718  0.385046  0.688442  0.786872  0.702929   
...                            ...       ...       ...       ...       ...   
qtz_train_015s_625-620    0.003787  0.043815  0.070439  0.077455  0.067289   
qtz_train_015s_625-621    0.004155  0.043077  0.068879  0.075580  0.065538   
qtz_train_015s_625-622    0.003540  0.042567  0.068623  0.075576  0.065634   
qtz_train_015s_625-623    0.003601  0.043714  0.070567  0.077919  0.068031   
qtz_train_015s_625-624    0.004089  0.042137  0.067314  0.073799  0.063936   

  

c:\users\ntemi\venv-scnn\venv\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


model trained
fo_train_030s_5040-2963        0
qtz_train_003s_4760-2060       1
albite_train_015s_5250-709     0
an_train_015s_5600-3371        0
cal_train_1s_2732-477          0
                              ..
hb_train_120s_1225_02-683      0
bt_train_015s_5600-3534        0
bt_train_015s_5600-4365        0
mc_train_015s_5600-415         0
albite_train_015s_5250-5192    0
Name: label, Length: 57339, dtype: int64
1.0
Model label  0 
 [[49295     0]
 [    0  8044]] 



Model prectictions [[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.9987443320544123
Model label  0 
 [[12342     5]
 [   13  1975]] 



Model prectictions [[1.   0.  ]
 [1.   0.  ]
 [1.   0.  ]
 ...
 [0.96 0.04]
 [1.   0.  ]
 [1.   0.  ]]
in loop, label is 1 




c:\users\ntemi\venv-scnn\venv\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


model trained
gyp_train_15s_1680-462        0
albite_train_015s_5250-650    1
an_train_015s_5600-709        0
aug_train_030s_5600-3646      0
en_train_015s_5600-3620       0
                             ..
mc_train_015s_5600-5333       0
cal_train_1s_2732-284         0
cal_train_1s_2732-1115        0
ms_train_015s_6400-690        0
an_train_015s_5600-5192       0
Name: label, Length: 57339, dtype: int64
1.0
Model label  1 
 [[52624     0]
 [    0  4715]] 



Model prectictions [[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.9991628880362748
Model label  1 
 [[13170     5]
 [    7  1153]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
in loop, label is 2 




c:\users\ntemi\venv-scnn\venv\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


model trained
fo_train_030s_5040-2963        0
qtz_train_015s_625-454         0
albite_train_015s_5250-709     0
an_train_015s_5600-3371        0
cal_train_1s_2732-477          0
                              ..
mc_train_015s_5600-4512        0
bt_train_015s_5600-3534        0
bt_train_015s_5600-4365        0
mc_train_015s_5600-5469        0
albite_train_015s_5250-5192    0
Name: label, Length: 57339, dtype: int64
1.0
Model label  2 
 [[53272     0]
 [    0  4067]] 



Model prectictions [[1.   0.  ]
 [1.   0.  ]
 [1.   0.  ]
 ...
 [1.   0.  ]
 [0.99 0.01]
 [1.   0.  ]]
0.9934426229508196
Model label  2 
 [[13323    25]
 [   69   918]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
in loop, label is 3 




c:\users\ntemi\venv-scnn\venv\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


model trained
gyp_train_15s_1680-1412        0
bt_train_015s_5600-1600        1
albite_train_015s_5250-709     0
an_train_015s_5600-3371        0
en_train_015s_5600-4570        0
                              ..
ms_train_015s_6400-683         0
cal_train_1s_2732-1234         0
cal_train_1s_2732-2065         0
ms_train_015s_6400-1640        0
albite_train_015s_5250-5192    0
Name: label, Length: 57339, dtype: int64
1.0
Model label  3 
 [[51863     0]
 [    0  5476]] 



Model prectictions [[1.   0.  ]
 [0.07 0.93]
 [1.   0.  ]
 ...
 [1.   0.  ]
 [1.   0.  ]
 [1.   0.  ]]
0.9907917683990234
Model label  3 
 [[12932    54]
 [   78  1271]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
in loop, label is 4 




c:\users\ntemi\venv-scnn\venv\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


model trained
fo_train_030s_5040-2963        0
ms_train_015s_6400-1175        1
albite_train_015s_5250-709     0
an_train_015s_5600-3371        0
cal_train_1s_2732-477          0
                              ..
hb_train_120s_1225_02-683      0
bt_train_015s_5600-3534        0
bt_train_015s_5600-4365        0
mc_train_015s_5600-415         0
albite_train_015s_5250-5192    0
Name: label, Length: 57339, dtype: int64
1.0
Model label  4 
 [[52204     0]
 [    0  5135]] 



Model prectictions [[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.9988838507150332
Model label  4 
 [[13062     8]
 [    8  1257]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
in loop, label is 5 




c:\users\ntemi\venv-scnn\venv\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


model trained
gyp_train_12s_3336-2963        0
qtz_train_015s_625-440         0
albite_train_015s_5250-709     0
an_train_015s_5600-3371        0
cal_train_1s_2732-477          0
                              ..
mc_train_015s_5600-4498        0
bt_train_015s_5600-3534        0
bt_train_015s_5600-4365        0
mc_train_015s_5600-5455        0
albite_train_015s_5250-5192    0
Name: label, Length: 57339, dtype: int64
1.0
Model label  5 
 [[53284     0]
 [    0  4055]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.9997907220090687
Model label  5 
 [[13349     1]
 [    2   983]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
in loop, label is 6 




c:\users\ntemi\venv-scnn\venv\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


model trained
gyp_train_15s_1680-187         0
aug_train_030s_5600-375        1
albite_train_015s_5250-709     0
an_train_015s_5600-3371        0
en_train_015s_5600-3345        0
                              ..
mc_train_015s_5600-5058        0
cal_train_1s_2732-9            0
cal_train_1s_2732-840          0
ms_train_015s_6400-415         0
albite_train_015s_5250-5192    0
Name: label, Length: 57339, dtype: int64
1.0
Model label  6 
 [[52831     0]
 [    0  4508]] 



Model prectictions [[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.9978374607603767
Model label  6 
 [[13231    12]
 [   19  1073]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
in loop, label is 7 




c:\users\ntemi\venv-scnn\venv\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


model trained
gyp_train_15s_1680-187         0
en_train_015s_5600-375         1
albite_train_015s_5250-709     0
an_train_015s_5600-3371        0
cal_train_1s_2732-477          0
                              ..
mc_train_015s_5600-5058        0
bt_train_015s_5600-3534        0
bt_train_015s_5600-4365        0
ms_train_015s_6400-415         0
albite_train_015s_5250-5192    0
Name: label, Length: 57339, dtype: int64
1.0
Model label  7 
 [[52831     0]
 [    0  4508]] 



Model prectictions [[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.9991628880362748
Model label  7 
 [[13240     3]
 [    9  1083]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
in loop, label is 8 




c:\users\ntemi\venv-scnn\venv\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


model trained
gyp_train_15s_1680-187         0
an_train_015s_5600-375         1
albite_train_015s_5250-709     0
aug_train_030s_5600-3371       0
en_train_015s_5600-3345        0
                              ..
mc_train_015s_5600-5058        0
cal_train_1s_2732-9            0
cal_train_1s_2732-840          0
ms_train_015s_6400-415         0
albite_train_015s_5250-5192    0
Name: label, Length: 57339, dtype: int64
1.0
Model label  8 
 [[52831     0]
 [    0  4508]] 



Model prectictions [[1.   0.  ]
 [0.01 0.99]
 [1.   0.  ]
 ...
 [1.   0.  ]
 [1.   0.  ]
 [1.   0.  ]]
0.9943494942448553
Model label  8 
 [[13236     7]
 [   74  1018]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
in loop, label is 9 




c:\users\ntemi\venv-scnn\venv\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


model trained
fo_train_030s_5040-2963        0
mc_train_015s_5600-375         1
albite_train_015s_5250-709     0
an_train_015s_5600-3371        0
cal_train_1s_2732-477          0
                              ..
hb_train_120s_1225_02-683      0
bt_train_015s_5600-3534        0
bt_train_015s_5600-4365        0
ms_train_015s_6400-415         0
albite_train_015s_5250-5192    0
Name: label, Length: 57339, dtype: int64
1.0
Model label  9 
 [[52831     0]
 [    0  4508]] 



Model prectictions [[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.9967213114754099
Model label  9 
 [[13227    16]
 [   31  1061]] 



Model prectictions [[0.99 0.01]
 [1.   0.  ]
 [1.   0.  ]
 ...
 [1.   0.  ]
 [1.   0.  ]
 [1.   0.  ]]
in loop, label is 10 




c:\users\ntemi\venv-scnn\venv\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


model trained
gyp_train_12s_3336-2955        0
qtz_train_015s_625-432         0
albite_train_015s_5250-709     0
an_train_015s_5600-3371        0
en_train_015s_5600-2777        0
                              ..
mc_train_015s_5600-4490        0
bt_train_015s_5600-3534        0
bt_train_015s_5600-4365        0
mc_train_015s_5600-5447        0
albite_train_015s_5250-5192    0
Name: label, Length: 57339, dtype: int64
1.0
Model label  10 
 [[53292     0]
 [    0  4047]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.9996512033484478
Model label  10 
 [[13350     0]
 [    5   980]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
in loop, label is 11 




c:\users\ntemi\venv-scnn\venv\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


model trained
fo_train_030s_5040-2963        0
qtz_train_015s_625-416         0
albite_train_015s_5250-709     0
an_train_015s_5600-3371        0
cal_train_1s_2732-477          0
                              ..
mc_train_015s_5600-4474        0
bt_train_015s_5600-3534        0
bt_train_015s_5600-4365        0
mc_train_015s_5600-5431        0
albite_train_015s_5250-5192    0
Name: label, Length: 57339, dtype: int64
1.0
Model label  11 
 [[53305     0]
 [    0  4034]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
0.9998604813393791
Model label  11 
 [[13352     1]
 [    1   981]] 



Model prectictions [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


IndexError: list index out of range

# **Test the model! Outside of function scope!**

In [ ]:

#test data path - do not include /content/.../ML Spectroscopy/
testin_path=r'Data/Preprocessed/Continuous Wavelet Transformation/Test Set/Labeled/'

#build test set, drops samples with Null values
test_df=h.dfbuilder(testin_path,synth=synth,split_df=False,use_trash=trash)
test_df.dropna(inplace=True)

#separates features and labels
y_test=test_df[test_df.columns[-1]]
X_test=test_df.drop(test_df.columns[-1],axis=1).values

roc_out=h.roc_all(cnn_model.predict(X_test),y_test)

if not fast:
  roc_out.to_csv(mout_path+id_value+'roc_data.csv')

#tests model, you can also use model.predict outside of this scope
cnn_cwt.test_cnn_model(cnn_model,X_test,y_test,id_value)

#this is that old folder we were talking about where CNN.csv files get saved, i just commented it out and pointed it to the folder with the rest of the outputs
#saved_data=r'/content/drive/My Drive/ML Spectroscopy/Programs/Data Processing/Saved Lists/'
saved_data=r'/content/drive/My Drive/ML Spectroscopy/Model Data/CNN Model/'
pd.DataFrame(data=cnn_model.predict(X_test),index=test_df.index.values).to_csv(saved_data+id_value+r'CNN.csv')


# Play space for whatever other training/testing you want to do


Testing/Training Parameters

In [ ]:

'''define the hyperparameters here!'''
learning_rate=0.001
batch_size=100
drop_rate=0.55
epochs=50

#don't change the line below
hyperparameters=[learning_rate,batch_size,drop_rate,epochs]


In [ ]:

'''define other parameters here!'''
#this string is prepended to all output files for identification
id_value='multi_size_granite_only_update_with_probs'

#training data file path (do not include /content/drive/My Drive/ML Spectroscopy/)
fin_path=r'Data/Preprocessed/Continuous Wavelet Transformation/Labeled/'

#output file path for the trained model data
mout_path=r'Model Data/CNN Model/'

#proportion of the training data allocated to the dev set - a float x: 0<x<1
dev_size=0.2

#random seed used for train/dev split to ensure repeatable outcomes. None 
#provides a psuedorandom value that won't be repeatable
r_state=1

#fast - True for doing quick training that does not output probability weights
#for each sample during training. False for doing deep analysis and tracking
fast=False

#trash - True for using trash data in the model
trash=False

#threshold - float in the range [0.0,1.0) determines the discrimination threshold
threshold=0.0


Build a test set with out of class samples (RRUFF untrained data) and our in class test data set

In [ ]:
"""
#test data path - do not include /content/.../ML Spectroscopy/
testin_path1=r'Data/Preprocessed/Continuous Wavelet Transformation/Test Set/Labeled/'

#build test set, drops samples with Null values
test_df1=h.dfbuilder(testin_path1,synth=synth,split_df=False)
test_df1.dropna(inplace=True)


#test data path - do not include /content/.../ML Spectroscopy/
testin_path2=r'Data/Preprocessed/Continuous Wavelet Transformation/Test Set/RRUFF_untrained/Labeled/'

#build test set, drops samples with Null values
test_df2=h.dfbuilder(testin_path2,synth=True,split_df=False)
test_df2.dropna(inplace=True)

test_df=pd.concat([test_df1,test_df2])

test_df.loc[test_df['label']==9]=6

y_test=test_df[test_df.columns[-1]]
X_test=test_df.drop(test_df.columns[-1],axis=1).values
"""


Build test set with just granite data

In [ ]:

#test data path - do not include /content/.../ML Spectroscopy/
testin_path=r'Data/Preprocessed/Continuous Wavelet Transformation/Test Set/Labeled/'

#build test set, drops samples with Null values
test_df=h.dfbuilder(testin_path,synth=False,split_df=False)
test_df.dropna(inplace=True)

print(test_df)
y_test=test_df[test_df.columns[-1]]
X_test=test_df.drop(test_df.columns[-1],axis=1).values


Running model with limited data sets

In [ ]:

fin_path=r'Data/Preprocessed/Continuous Wavelet Transformation/Labeled/Limited Sizes/'

for i in [1,2,4,8,16,32,64,128,256,512,1024,2048,4096]:
  #adjusting some parameters for the size
  hyperparameters[1]=max([1,round(((i*9*4)/5)/411)])
  temp_id=id_value+str(i)
  
  print('\n\n\n\n', 'Model ',i,'\n')
  cnn_model=cwt_cnn_model(fin_path+str(i)+'/',mout_path,dev_size,r_state,hyperparameters,fast,temp_id,use_trash=trash,threshold=threshold)
  print('\nTest CM\n')
  cnn_cwt.test_cnn_model(cnn_model,X_test,y_test,temp_id,test=True,threshold=threshold,fast=fast)



In [ ]:
#print(roc_out)

In [ ]:
"""
opt_thresh=np.array((roc_out.columns.values.astype(float)))
for i in range(len(roc_out.columns)):
  tpr_ls,fpr_ls,thresh_ls=roc_out[roc_out.columns.values[i]]
  #print(np.subtract(tpr_ls,fpr_ls))
  opt_thresh[i]=thresh_ls[np.argmax(np.subtract(tpr_ls,fpr_ls))]
  print('Optimal Threshold for class:',roc_out.columns.values[i],'\n',opt_thresh[i])
print(opt_thresh.sum()*(1.0/len(opt_thresh)))
"""

In [ ]:
"""
#tests model, you can also use model.predict outside of this scope
cnn_cwt.test_cnn_model(cnn_model,X_test,y_test,id_value,.0,fast=True)
"""

In [ ]:
#report metrics: precision, recall, f1-score, support for test set
from sklearn.metrics import classification_report
print(classification_report(y_test,cnn_cwt.dec_pred(cnn_model.predict(X_test),threshold)))
